services:
  logstash:
    volumes:
      - ./config/logstash-http/output-to-es.conf:/pipeline/output-to-es.conf:ro
    environment:
      LS_JAVA_OPTS: "-Xms2g -Xmx2g"
  stats-logstash:
    volumes:
      - ./config/logstash-stats/output-to-es.conf:/pipeline/output-to-es.conf:ro
