http:
  max_content_length: 200MB
  pipelining:
    max_events: 100000

path:
  data: /usr/share/elasticsearch/data

discovery:
  type: single-node

network:
  host: 0

xpack.security:
  enabled: true
  http.ssl:
    enabled: true
    key: certs/es/es.key
    certificate: certs/es/es.crt
    certificate_authorities: certs/ca/ca.crt
