http:
  #  port: 9200
  max_content_length: 200MB
  pipelining:
    max_events: 100000

xpack.security.enabled: false

path:
  data: /usr/share/elasticsearch/data

discovery:
  type: single-node

network:
  host: 0
