input {
    http {
        port => 8080
        additional_codecs => { "application/json" => "json_lines" }
    }
}

filter {
  if [@metadata][input][http][request][headers][x_api_key] != "${SECRET_KEY}" {
       drop { }
  }
}
